version: '3.8'

services:
  ui:
    container_name: ui-container
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - NODE_VERSION=20
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      #- poc_node_modules:/app/node_modules
    command: npm run dev
    env_file:
      - .env.local

volumes:
  poc_node_modules:
    name: poc_node_modules_volume