name: Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      
      - name: Create account private key file
        run: echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > key.json
      
      - name: Export file
        run: export GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/key.json

      - name: Deploy to Firebase hosting
        run: firebase deploy -P dev 
