name: Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # - name: Check if GOOGLE_APPLICATION_CREDENTIALS points
      #   run: echo $GOOGLE_APPLICATION_CREDENTIALS

      # - name: cat GOOGLE_APPLICATION_CREDENTIALS 
      #   run: cat $GOOGLE_APPLICATION_CREDENTIALS
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Firebase Tools
        #run: npm install -g firebase-tools
        run: curl -sL https://firebase.tools | bash
      
      - name: Deploy to Firebase hosting
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > "google-application-credentials.json"
          echo $GOOGLE_APPLICATION_CREDENTIALS
          cat $GOOGLE_APPLICATION_CREDENTIALS
          firebase use dev --debug
      
      #firebase deploy -P dev --non-interactive

      # - name: Deploy to Firebase hosting
      #   run: firebase deploy -P dev --non-interactive
