name: Deploy to DEV

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Firebase Tools
        #run: npm install -g firebase-tools
        run: curl -sL https://firebase.tools | bash
      
      - name: Prepare creds
        shell: bash
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > "google-application-credentials.json"
      
      - name: Deploy to Firebase hosting
        shell: bash
        run: |
          firebase use dev
          firebase deploy -P dev --non-interactive

  